---
- name: this is for an install of httpd
  hosts: dev
  become: true
  gather_facts: yes
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest
    
         
