---
- name: this is for an install of httpd
  hosts: dev
  become: true
  become_user: ansible
  gather_facts: yes
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: start httpd
      ansible.builtin.yum:
        name: httpd
        state: started
         
